version: '3.9'

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  api:
    extends:
      file: docker-compose.yml
      service: api
    entrypoint: ["/bin/sh", "-c", "/scripts/init_db.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

  web:
    extends:
      file: docker-compose.yml
      service: web
    command: pnpm --dir /app dev --hostname 0.0.0.0 --port 3000
