version: '3.9'

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  api:
    extends:
      file: docker-compose.yml
      service: api
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    command: python manage.py runserver 0.0.0.0:8000

  web:
    extends:
      file: docker-compose.yml
      service: web
    command: pnpm --dir /app dev --hostname 0.0.0.0 --port 3000
