# Generated by Django 6.0.2 on 2026-03-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_url', models.TextField()),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=4)),
                ('orgao_origem', models.CharField(max_length=100)),
                ('competencia', models.DateField()),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('processados', models.PositiveIntegerField(default=0)),
                ('nao_encontrados', models.PositiveIntegerField(default=0)),
                ('erros', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('resultado_resumo', models.JSONField(blank=True, default=dict)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos_retorno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoRetornoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('linha_numero', models.PositiveIntegerField()),
                ('cpf_cnpj', models.CharField(max_length=18)),
                ('matricula_servidor', models.CharField(max_length=50)),
                ('nome_servidor', models.CharField(max_length=255)),
                ('competencia', models.CharField(max_length=7)),
                ('valor_descontado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status_desconto', models.CharField(choices=[('efetivado', 'Efetivado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('processado', models.BooleanField(default=False)),
                ('resultado_processamento', models.CharField(choices=[('baixa_efetuada', 'Baixa efetuada'), ('nao_descontado', 'Não descontado'), ('nao_encontrado', 'Não encontrado'), ('erro', 'Erro'), ('ciclo_aberto', 'Ciclo aberto')], default='ciclo_aberto', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('arquivo_retorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='importacao.arquivoretorno')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_retorno', to='associados.associado')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_retorno', to='contratos.parcela')),
            ],
            options={
                'ordering': ['linha_numero'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('upload', 'Upload'), ('parse', 'Parse'), ('validacao', 'Validação'), ('reconciliacao', 'Reconciliação'), ('baixa', 'Baixa'), ('erro', 'Erro')], max_length=20)),
                ('mensagem', models.TextField()),
                ('dados', models.JSONField(blank=True, null=True)),
                ('arquivo_retorno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='importacao.arquivoretorno')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
