# Generated by Django 6.0.2 on 2026-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='cargo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='gerou_encerramento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='gerou_novo_ciclo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='orgao_codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='orgao_pagto_codigo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='orgao_pagto_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='payload_bruto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='status_codigo',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='status_descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='arquivoretorno',
            name='formato',
            field=models.CharField(choices=[('txt', 'TXT'), ('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=4),
        ),
        migrations.AlterField(
            model_name='arquivoretornoitem',
            name='resultado_processamento',
            field=models.CharField(choices=[('baixa_efetuada', 'Baixa efetuada'), ('nao_descontado', 'Não descontado'), ('pendencia_manual', 'Pendência manual'), ('nao_encontrado', 'Não encontrado'), ('erro', 'Erro'), ('ciclo_aberto', 'Ciclo aberto')], default='ciclo_aberto', max_length=30),
        ),
    ]
