# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
        ('importacao', '0002_arquivoretornoitem_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('import_uuid', models.CharField(max_length=36)),
                ('referencia_month', models.DateField()),
                ('status_code', models.CharField(blank=True, max_length=2)),
                ('matricula', models.CharField(blank=True, max_length=40)),
                ('orgao_pagto', models.CharField(blank=True, max_length=40)),
                ('nome_relatorio', models.CharField(blank=True, max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('esperado_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recebido_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_status', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], max_length=20, null=True)),
                ('agente_refi_solicitado', models.BooleanField(default=False)),
                ('manual_paid_at', models.DateTimeField(blank=True, null=True)),
                ('manual_forma_pagamento', models.CharField(blank=True, max_length=40)),
                ('manual_comprovante_path', models.CharField(blank=True, max_length=500)),
                ('source_file_path', models.CharField(blank=True, max_length=500)),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_mensalidades', to='associados.associado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_mensalidades_criados', to=settings.AUTH_USER_MODEL)),
                ('manual_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_mensalidades_manuais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-referencia_month', 'cpf_cnpj'],
                'indexes': [models.Index(fields=['cpf_cnpj', 'referencia_month'], name='importacao__cpf_cnp_c53f70_idx'), models.Index(fields=['import_uuid'], name='importacao__import__a1afba_idx')],
            },
        ),
    ]
