# Generated by Django 6.0.2 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0003_pagamentomensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoretorno',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivoretornoitem',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaolog',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamentomensalidade',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
