# Generated by Django 6.0.2 on 2026-03-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importacao", "0004_arquivoretorno_data_referencia_negocio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arquivoretorno",
            name="formato",
            field=models.CharField(
                choices=[
                    ("txt", "TXT"),
                    ("csv", "CSV"),
                    ("xlsx", "XLSX"),
                    ("man", "Manual"),
                ],
                max_length=4,
            ),
        ),
    ]
