# Generated by Django 5.0.4 on 2026-03-27 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0011_adminoverrideevent_adminoverridechange'),
        ('contratos', '0008_contrato_admin_manual_layout_enabled_and_more'),
        ('importacao', '0005_alter_arquivoretorno_formato'),
        ('tesouraria', '0013_alter_devolucaoassociado_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoretornoitem',
            name='resultado_processamento',
            field=models.CharField(choices=[('baixa_efetuada', 'Baixa efetuada'), ('nao_descontado', 'Não descontado'), ('pendencia_manual', 'Pendência manual'), ('duplicidade', 'Duplicidade'), ('nao_encontrado', 'Não encontrado'), ('erro', 'Erro'), ('ciclo_aberto', 'Ciclo aberto')], default='ciclo_aberto', max_length=30),
        ),
        migrations.CreateModel(
            name='DuplicidadeFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('motivo', models.CharField(choices=[('baixa_manual_duplicada', 'Baixa manual duplicada'), ('baixa_manual_mes_errado', 'Baixa manual em mês errado'), ('divergencia_valor', 'Divergência de valor'), ('conflito_retorno', 'Conflito vindo do retorno')], max_length=40)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_tratamento', 'Em tratamento'), ('resolvida', 'Resolvida'), ('descartada', 'Descartada')], default='aberta', max_length=20)),
                ('competencia_retorno', models.DateField()),
                ('competencia_manual', models.DateField(blank=True, null=True)),
                ('valor_retorno', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_resolucao', models.TextField(blank=True)),
                ('arquivo_retorno_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras', to='importacao.arquivoretornoitem')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras', to='associados.associado')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras', to='contratos.contrato')),
                ('devolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras', to='tesouraria.devolucaoassociado')),
                ('pagamento_mensalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras', to='importacao.pagamentomensalidade')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicidades_financeiras_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'motivo'], name='importacao__status_eb476f_idx'), models.Index(fields=['competencia_retorno'], name='importacao__compete_6900b0_idx')],
            },
        ),
    ]
