# Generated by Django 6.0.2 on 2026-03-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('orgao_publico', models.CharField(max_length=150)),
                ('matricula_orgao', models.CharField(max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('cadastrado', 'Cadastrado'), ('em_analise', 'Em análise'), ('ativo', 'Ativo'), ('pendente', 'Pendente'), ('inativo', 'Inativo')], default='cadastrado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('agente_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='associados_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ContatoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome_contato', models.CharField(max_length=255)),
                ('parentesco', models.CharField(blank=True, max_length=100)),
                ('telefone_contato', models.CharField(max_length=20)),
                ('ultima_interacao_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('associado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contato_historico', to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('banco', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=20)),
                ('conta', models.CharField(max_length=30)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], default='corrente', max_length=20)),
                ('chave_pix', models.CharField(blank=True, max_length=120)),
                ('associado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_bancarios', to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('comprovante_residencia', 'Comprovante de residência'), ('contracheque', 'Contracheque'), ('outro', 'Outro')], max_length=40)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='associados.associado')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('associado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='associados.associado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
