# Generated by Django 6.0.2 on 2026-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('uniao_estavel', 'União estável')], max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='associado',
            name='profissao',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='associado',
            name='rg',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=10),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='matricula_servidor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='orgao_publico',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='situacao_servidor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='associado',
            name='matricula_orgao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='associado',
            name='orgao_publico',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(choices=[('cadastrado', 'Cadastrado'), ('em_analise', 'Em análise'), ('ativo', 'Ativo'), ('pendente', 'Pendente'), ('inativo', 'Inativo'), ('inadimplente', 'Inadimplente')], default='cadastrado', max_length=20),
        ),
        migrations.AlterField(
            model_name='contatohistorico',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contatohistorico',
            name='telefone_contato',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_conta',
            field=models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança'), ('salario', 'Salário')], default='corrente', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('rg', 'RG'), ('cpf', 'CPF'), ('documento_frente', 'Documento (frente)'), ('documento_verso', 'Documento (verso)'), ('comprovante_residencia', 'Comprovante de residência'), ('divulgacao', 'Divulgação'), ('contracheque', 'Contracheque'), ('termo_adesao', 'Termo de adesão'), ('termo_antecipacao', 'Termo de antecipação'), ('outro', 'Outro')], max_length=40),
        ),
    ]
