# Generated by Django 6.0.2 on 2026-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_associado_estado_civil_associado_orgao_expedidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='agente_filial',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio_taxa',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
