# Generated by Django 6.0.2 on 2026-03-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='matricula_orgao',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='associado',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='associado',
            name='orgao_publico',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='associado',
            name='rg',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='associado',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=60),
        ),
    ]
