# Generated by Django 5.0.4 on 2026-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0005_alter_endereco_numero_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='agencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='anticipations_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio_data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='bairro',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='associado',
            name='banco',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='associado',
            name='calc_liquido_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='calc_mensalidade_associativa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='calc_prazo_antecipacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='calc_valor_bruto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='cep',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='associado',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='associado',
            name='cidade',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='associado',
            name='complemento',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='associado',
            name='conta',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_codigo_contrato',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_data_envio_primeira',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_doacao_associado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_margem_disponivel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_mensalidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_mes_averbacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_prazo_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_status_contrato',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_taxa_antecipacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contrato_valor_antecipacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='documents_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='associado',
            name='numero',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='associado',
            name='situacao_servidor',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='associado',
            name='tipo_conta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
