# Generated by Django 6.0.2 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0007_associado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contatohistorico',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
