# Generated by Django 5.0.4 on 2026-03-19 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0009_documento_reference_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='aceite_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio1_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio1_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio2_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='auxilio2_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='contato_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='associado',
            name='contato_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associado',
            name='termo_adesao_admin_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='associado',
            name='termo_antecipacao_admin_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Auxilio2Filiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('charge_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('loc_id', models.BigIntegerField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('imagem_qrcode', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxilio2_filiacoes', to='associados.associado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxilio2_filiacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='associados__user_id_0aaaf9_idx'), models.Index(fields=['charge_id'], name='associados__charge__0f861f_idx')],
            },
        ),
    ]
