# Generated by Django 6.0.2 on 2026-03-22 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0010_associado_aceite_termos_associado_auxilio1_status_and_more'),
        ('contratos', '0008_contrato_admin_manual_layout_enabled_and_more'),
        ('refinanciamento', '0010_comprovante_status_validacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOverrideEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escopo', models.CharField(choices=[('associado', 'Associado'), ('contrato', 'Contrato'), ('ciclos', 'Ciclos'), ('refinanciamento', 'Refinanciamento'), ('esteira', 'Esteira'), ('documento', 'Documento'), ('comprovante', 'Comprovante')], max_length=32)),
                ('resumo', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('confirmacao_dupla', models.BooleanField(default=True)),
                ('revertida_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_reversao', models.TextField(blank=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_override_events', to='associados.associado')),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='contratos.ciclo')),
                ('comprovante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='refinanciamento.comprovante')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='contratos.contrato')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='associados.documento')),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='contratos.parcela')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_override_events', to=settings.AUTH_USER_MODEL)),
                ('refinanciamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_override_events', to='refinanciamento.refinanciamento')),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_override_reversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminOverrideChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entity_type', models.CharField(choices=[('associado', 'Associado'), ('contrato', 'Contrato'), ('ciclo', 'Ciclo'), ('parcela', 'Parcela'), ('refinanciamento', 'Refinanciamento'), ('documento', 'Documento'), ('comprovante', 'Comprovante'), ('esteira', 'Esteira')], max_length=32)),
                ('entity_id', models.PositiveIntegerField()),
                ('competencia_referencia', models.DateField(blank=True, null=True)),
                ('resumo', models.CharField(max_length=255)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='associados.adminoverrideevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
