# Generated by Django 6.0.2 on 2026-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0013_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='status',
            field=models.CharField(choices=[('cadastrado', 'Cadastrado'), ('importado', 'Importado'), ('em_analise', 'Em análise'), ('ativo', 'Ativo'), ('apto_a_renovar', 'Apto a renovar'), ('pendente', 'Pendente'), ('inativo', 'Inativo'), ('inadimplente', 'Inadimplente')], default='cadastrado', max_length=20),
        ),
    ]
