# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_despesa', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], max_length=20)),
                ('recorrencia', models.CharField(choices=[('nenhuma', 'Nenhuma'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='nenhuma', max_length=20)),
                ('recorrencia_ativa', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('comprovantes_json', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_despesa'],
            },
        ),
    ]
