# Generated by Django 6.0.2 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_despesa_data_referencia_negocio"),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="anexo",
            field=models.FileField(blank=True, null=True, upload_to="despesas/"),
        ),
        migrations.AddField(
            model_name="despesa",
            name="nome_anexo",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="despesa",
            name="status_anexo",
            field=models.CharField(
                choices=[("pendente", "Pendente"), ("anexado", "Anexado")],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
