# Generated by Django 5.0.4 on 2026-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_despesa_anexo_status_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
