# Generated by Django 6.0.2 on 2026-03-11 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
        ('contratos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('competencia_solicitada', models.DateField()),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('efetivado', 'Efetivado')], default='solicitado', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos', to='associados.associado')),
                ('contrato_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos', to='contratos.contrato')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('pix', 'PIX'), ('contrato', 'Contrato'), ('outro', 'Outro')], default='pix', max_length=20)),
                ('arquivo', models.FileField(upload_to='refinanciamentos/')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprovantes_refinanciamento', to=settings.AUTH_USER_MODEL)),
                ('refinanciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='refinanciamento.refinanciamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
