# Generated by Django 6.0.2 on 2026-03-11 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_auxilio_liberado_em_contrato_contato_web_and_more'),
        ('refinanciamento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprovante',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='refinanciamento',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comprovante',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='nome_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='papel',
            field=models.CharField(choices=[('associado', 'Associado'), ('agente', 'Agente')], default='associado', max_length=20),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='bloqueado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='ciclo_destino',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamento_destino', to='contratos.ciclo'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='ciclo_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_origem', to='contratos.ciclo'),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='efetivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_efetivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='executado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='motivo_bloqueio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='repasse_agente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='valor_refinanciamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='refinanciamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='refinanciamento.refinanciamento'),
        ),
        migrations.AlterField(
            model_name='refinanciamento',
            name='status',
            field=models.CharField(choices=[('pendente_apto', 'Pendente apto'), ('bloqueado', 'Bloqueado'), ('concluido', 'Concluído'), ('revertido', 'Revertido'), ('efetivado', 'Efetivado'), ('solicitado', 'Solicitado'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente_apto', max_length=20),
        ),
    ]
