# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
        ('importacao', '0003_pagamentomensalidade'),
        ('refinanciamento', '0002_alter_comprovante_options_and_more'),
        ('tesouraria', '0003_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='agente_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='filial_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='agente_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='analista_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='contrato_codigo_novo',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='contrato_codigo_origem',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='coordenador_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='cpf_cnpj_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='cycle_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='filial_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='mode',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='nome_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='parcelas_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='parcelas_ok',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='ref1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='ref2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='ref3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refinanciamentos_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='termo_antecipacao_mime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='termo_antecipacao_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='termo_antecipacao_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='termo_antecipacao_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='termo_antecipacao_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AjusteValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('origem', models.CharField(blank=True, max_length=10)),
                ('fonte_base', models.CharField(blank=True, max_length=10)),
                ('valor_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_novo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tp_margem', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ac_margem', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('a2_margem', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('motivo', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_valor_criados', to=settings.AUTH_USER_MODEL)),
                ('refinanciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_valor', to='refinanciamento.refinanciamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('request_key', models.CharField(max_length=80)),
                ('refs_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('liberado', 'Liberado'), ('assumido', 'Assumido'), ('finalizado', 'Finalizado')], default='liberado', max_length=20)),
                ('solicitado_em', models.DateTimeField(blank=True, null=True)),
                ('liberado_em', models.DateTimeField(blank=True, null=True)),
                ('assumido_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('analista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refi_assumptions_assumidas', to=settings.AUTH_USER_MODEL)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refi_assumptions', to='associados.associado')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refi_assumptions_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('referencia_month', models.DateField()),
                ('status_code', models.CharField(blank=True, max_length=2)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('import_uuid', models.CharField(blank=True, max_length=36)),
                ('source_file_path', models.CharField(blank=True, max_length=500)),
                ('pagamento_mensalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refi_itens', to='importacao.pagamentomensalidade')),
                ('refinanciamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='refinanciamento.refinanciamento')),
                ('tesouraria_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refi_itens', to='tesouraria.pagamento')),
            ],
            options={
                'ordering': ['refinanciamento_id', 'referencia_month'],
            },
        ),
    ]
