# Generated by Django 6.0.2 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinanciamento', '0003_comprovante_agente_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustevalor',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assumption',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
