# Generated by Django 5.0.4 on 2026-03-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_parcela_status'),
        ('refinanciamento', '0005_refinanciamento_ref4'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='contratos.ciclo'),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='mime',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='origem',
            field=models.CharField(choices=[('efetivacao_contrato', 'Efetivação do contrato'), ('analise_renovacao', 'Análise da renovação'), ('tesouraria_renovacao', 'Tesouraria da renovação'), ('legado', 'Legado'), ('outro', 'Outro')], default='outro', max_length=40),
        ),
        migrations.AddField(
            model_name='comprovante',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='papel',
            field=models.CharField(choices=[('associado', 'Associado'), ('agente', 'Agente'), ('operacional', 'Operacional')], default='associado', max_length=20),
        ),
        migrations.AlterField(
            model_name='comprovante',
            name='tipo',
            field=models.CharField(choices=[('pix', 'PIX'), ('contrato', 'Contrato'), ('termo_antecipacao', 'Termo de antecipação'), ('comprovante_pagamento_associado', 'Comprovante pagamento associado'), ('comprovante_pagamento_agente', 'Comprovante pagamento agente'), ('outro', 'Outro')], default='pix', max_length=40),
        ),
        migrations.AlterField(
            model_name='refinanciamento',
            name='status',
            field=models.CharField(choices=[('apto_a_renovar', 'Apto a renovar'), ('em_analise_renovacao', 'Em análise para renovação'), ('aprovado_para_renovacao', 'Aprovado para renovação'), ('pendente_apto', 'Pendente apto'), ('bloqueado', 'Bloqueado'), ('concluido', 'Concluído'), ('desativado', 'Desativado'), ('revertido', 'Revertido'), ('efetivado', 'Efetivado'), ('solicitado', 'Solicitado'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente_apto', max_length=40),
        ),
    ]
