# Generated by Django 5.0.4 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinanciamento', '0006_comprovante_ciclo_comprovante_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='legacy_comprovante_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='data_ativacao_ciclo',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='legacy_refinanciamento_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='refinanciamento',
            name='origem',
            field=models.CharField(choices=[('legado', 'Legado'), ('operacional', 'Operacional')], default='operacional', max_length=20),
        ),
    ]
