# Generated by Django 5.0.4 on 2026-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinanciamento', '0007_legacy_ledger_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='arquivo_referencia_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
