# Generated by Django 6.0.2 on 2026-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinanciamento', '0009_renewal_flow_coordination'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprovante',
            name='status_validacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='pendente', max_length=20),
        ),
    ]
