# Generated by Django 5.0.4 on 2026-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refinanciamento', '0011_refinanciamento_status_solicitado_para_liquidacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refinanciamento',
            name='status',
            field=models.CharField(choices=[('apto_a_renovar', 'Apto a renovar'), ('solicitado_para_liquidacao', 'Solicitado para liquidação'), ('em_analise_renovacao', 'Em análise para renovação'), ('pendente_termo_analista', 'Pendente termo para o analista'), ('pendente_termo_agente', 'Pendente termo para o agente'), ('aprovado_analise_renovacao', 'Aprovado pela análise para renovação'), ('aprovado_para_renovacao', 'Aprovado para renovação'), ('pendente_apto', 'Pendente apto'), ('bloqueado', 'Bloqueado'), ('concluido', 'Concluído'), ('desativado', 'Desativado'), ('revertido', 'Revertido'), ('efetivado', 'Efetivado'), ('solicitado', 'Solicitado'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente_apto', max_length=40),
        ),
    ]
