# Generated by Django 6.0.2 on 2026-03-11 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EsteiraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status_atual', models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído'), ('pendencia', 'Pendência')], default='cadastro', max_length=20)),
                ('prioridade', models.PositiveSmallIntegerField(default=3)),
                ('assumido_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_analise', to=settings.AUTH_USER_MODEL)),
                ('associado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esteira_item', to='associados.associado')),
                ('coordenador_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_coordenacao', to=settings.AUTH_USER_MODEL)),
                ('tesoureiro_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_tesouraria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('resolvida', 'Resolvida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('retornado_para_agente', models.BooleanField(default=True)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('esteira_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='esteira.esteiraitem')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendencias_resolvidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('de_status', models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído'), ('pendencia', 'Pendência')], max_length=20)),
                ('para_status', models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído'), ('pendencia', 'Pendência')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('realizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('esteira_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes', to='esteira.esteiraitem')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transicoes_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-realizado_em'],
            },
        ),
    ]
