# Generated by Django 6.0.2 on 2026-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esteiraitem',
            name='etapa_atual',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído')], default='analise', max_length=20),
        ),
        migrations.AddField(
            model_name='esteiraitem',
            name='observacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='esteiraitem',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em andamento'), ('pendenciado', 'Pendenciado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aguardando', max_length=20),
        ),
        migrations.AddField(
            model_name='pendencia',
            name='tipo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='transicao',
            name='acao',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transicao',
            name='de_situacao',
            field=models.CharField(blank=True, choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em andamento'), ('pendenciado', 'Pendenciado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=20),
        ),
        migrations.AddField(
            model_name='transicao',
            name='para_situacao',
            field=models.CharField(blank=True, choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em andamento'), ('pendenciado', 'Pendenciado'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='esteiraitem',
            name='status_atual',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído')], default='analise', max_length=20),
        ),
        migrations.AlterField(
            model_name='transicao',
            name='de_status',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transicao',
            name='para_status',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('analise', 'Análise'), ('coordenacao', 'Coordenação'), ('tesouraria', 'Tesouraria'), ('concluido', 'Concluído')], max_length=20),
        ),
    ]
