# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
        ('esteira', '0002_esteiraitem_etapa_atual_esteiraitem_observacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esteiraitem',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('contrato_codigo', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('incomplete', 'Incompleto'), ('resolved', 'Resolvido')], default='incomplete', max_length=20)),
                ('mensagem', models.TextField()),
                ('documents_snapshot_json', models.JSONField(blank=True, null=True)),
                ('agent_uploads_json', models.JSONField(blank=True, null=True)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_issues_criados', to=settings.AUTH_USER_MODEL)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_issues', to='associados.associado')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocReupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('contrato_codigo', models.CharField(blank=True, max_length=80)),
                ('file_original_name', models.CharField(max_length=255)),
                ('file_stored_name', models.CharField(max_length=255)),
                ('file_relative_path', models.CharField(blank=True, max_length=500)),
                ('file_mime', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], default='received', max_length=20)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doc_reuploads', to='associados.associado')),
                ('doc_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuploads', to='esteira.docissue')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doc_reuploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
