# Generated by Django 6.0.2 on 2026-03-11 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=40, unique=True)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comissao_agente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('data_contrato', models.DateField(default=django.utils.timezone.now)),
                ('comprovante_pix', models.FileField(blank=True, null=True, upload_to='comprovantes_pix/')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_agenciados', to=settings.AUTH_USER_MODEL)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='associados.associado')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('ciclo_aberto', 'Ciclo aberto'), ('ciclo_renovado', 'Ciclo renovado'), ('apto_a_renovar', 'Apto a renovar'), ('encerrado', 'Encerrado')], default='ciclo_aberto', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='contratos.contrato')),
            ],
            options={
                'ordering': ['contrato_id', 'numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveSmallIntegerField()),
                ('referencia_mes', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('futuro', 'Futuro'), ('em_aberto', 'Em aberto'), ('descontado', 'Descontado'), ('nao_descontado', 'Não descontado'), ('cancelado', 'Cancelado')], default='futuro', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contratos.ciclo')),
            ],
            options={
                'ordering': ['ciclo_id', 'numero'],
                'unique_together': {('ciclo', 'numero')},
            },
        ),
    ]
