# Generated by Django 6.0.2 on 2026-03-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='auxilio_liberado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contato_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_aprovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_primeira_mensalidade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='doacao_associado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='margem_disponivel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contrato',
            name='mes_averbacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='prazo_meses',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contrato',
            name='taxa_antecipacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contrato',
            name='termos_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_total_antecipacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='status',
            field=models.CharField(choices=[('futuro', 'Futuro'), ('aberto', 'Aberto'), ('ciclo_renovado', 'Ciclo renovado'), ('apto_a_renovar', 'Apto a renovar'), ('fechado', 'Fechado')], default='futuro', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')], default='em_analise', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('futuro', 'Futuro'), ('em_aberto', 'Em aberto'), ('descontado', 'Descontado'), ('nao_descontado', 'Não descontado'), ('cancelado', 'Cancelado')], default='em_aberto', max_length=20),
        ),
    ]
