# Generated by Django 6.0.2 on 2026-03-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_parcela_associado_competencia_lock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='parcela',
            new_name='contratos_p_associa_58fcee_idx',
            old_name='contratos_p_associa_d43752_idx',
        ),
    ]
