# Generated by Django 6.0.2 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_rename_contratos_p_associa_d43752_idx_contratos_p_associa_58fcee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
