# Generated by Django 5.0.4 on 2026-03-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_ciclo_data_referencia_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('futuro', 'Futuro'), ('em_aberto', 'Em aberto'), ('em_previsao', 'Em previsão'), ('descontado', 'Descontado'), ('nao_descontado', 'Não descontado'), ('cancelado', 'Cancelado')], default='em_aberto', max_length=20),
        ),
    ]
