# Generated by Django 6.0.2 on 2026-03-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_parcela_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('futuro', 'Futuro'), ('em_aberto', 'Em aberto'), ('em_previsao', 'Em previsão'), ('descontado', 'Descontado'), ('liquidada', 'Liquidada'), ('nao_descontado', 'Não descontado'), ('cancelado', 'Cancelado')], default='em_aberto', max_length=20),
        ),
    ]
