# Generated by Django 6.0.2 on 2026-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_parcela_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='admin_manual_layout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='admin_manual_layout_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='layout_bucket',
            field=models.CharField(choices=[('cycle', 'No ciclo'), ('unpaid', 'Parcelas não descontadas'), ('movement', 'Movimento financeiro avulso')], default='cycle', max_length=20),
        ),
    ]
