# Generated by Django 5.0.4 on 2026-03-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0008_contrato_admin_manual_layout_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cancelamento_motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='cancelamento_tipo',
            field=models.CharField(blank=True, choices=[('cancelado', 'Cancelado'), ('desistente', 'Desistente')], default='', max_length=20),
        ),
    ]
