# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_set_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_path',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.CreateModel(
            name='AgenteMargemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('percentual', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigente_ate', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=190)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margem_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='margem_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='AgenteMargemHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('percentual_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentual_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('motivo', models.CharField(blank=True, max_length=190)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margem_historicos', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='margem_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgenteMargemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('percentual_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentual_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mensalidade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('margem_disponivel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auxilio_valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('auxilio_valor_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('motivo', models.CharField(blank=True, max_length=190)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margem_snapshots', to=settings.AUTH_USER_MODEL)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='margem_snapshots', to='associados.associado')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='margem_snapshot_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
