# Generated by Django 6.0.2 on 2026-03-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_set_password_user_profile_photo_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentemargemconfig',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentemargemhistorico',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentemargemsnapshot',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userrole',
            name='data_referencia_negocio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
