# Generated by Django 5.0.4 on 2026-03-27 07:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mobileaccesstoken_passwordresetrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoComissaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('percentual', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('vigente_ate', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=190)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_comissao_global_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoComissaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escopo', models.CharField(choices=[('global', 'Global'), ('agente', 'Agente')], max_length=20)),
                ('percentual_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentual_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('motivo', models.CharField(blank=True, max_length=190)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_comissao_historico', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuracoes_comissao_alteradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
