# Generated by Django 6.0.2 on 2026-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmacao',
            options={'ordering': ['contrato_id', 'competencia', 'tipo']},
        ),
        migrations.AddField(
            model_name='confirmacao',
            name='link_chamada',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='confirmacao',
            name='data_confirmacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
