# Generated by Django 6.0.2 on 2026-03-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_associado_agente_filial_associado_auxilio_status_and_more'),
        ('tesouraria', '0002_alter_confirmacao_options_confirmacao_link_chamada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('contrato_codigo', models.CharField(blank=True, max_length=80)),
                ('contrato_valor_antecipacao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contrato_margem_disponivel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('agente_responsavel', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pago', max_length=20)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=40)),
                ('comprovante_path', models.CharField(blank=True, max_length=500)),
                ('comprovante_associado_path', models.CharField(blank=True, max_length=500)),
                ('comprovante_agente_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tesouraria_pagamentos', to='associados.associado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tesouraria_pagamentos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
