# Generated by Django 6.0.2 on 2026-03-21 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_alter_parcela_status'),
        ('tesouraria', '0007_pagamentonotificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacaoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data_liquidacao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprovante', models.FileField(upload_to='liquidacoes_contrato/')),
                ('nome_comprovante', models.CharField(blank=True, max_length=255)),
                ('observacao', models.TextField(blank=True)),
                ('contrato_status_anterior', models.CharField(blank=True, max_length=20)),
                ('associado_status_anterior', models.CharField(blank=True, max_length=20)),
                ('revertida_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_reversao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacoes', to='contratos.contrato')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidacoes_revertidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacaoContratoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_referencia_negocio', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('numero_parcela', models.PositiveSmallIntegerField()),
                ('referencia_mes', models.DateField()),
                ('status_anterior', models.CharField(max_length=20)),
                ('data_pagamento_anterior', models.DateField(blank=True, null=True)),
                ('observacao_anterior', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('liquidacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='tesouraria.liquidacaocontrato')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacao_itens', to='contratos.parcela')),
            ],
            options={
                'ordering': ['referencia_mes', 'numero_parcela', 'id'],
            },
        ),
    ]
