# Generated by Django 6.0.2 on 2026-03-21 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associados", "0010_associado_aceite_termos_associado_auxilio1_status_and_more"),
        ("contratos", "0007_alter_parcela_status"),
        ("tesouraria", "0008_liquidacaocontrato_liquidacaocontratoitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevolucaoAssociado",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("data_referencia_negocio", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pagamento_indevido", "Pagamento indevido"),
                            ("desconto_indevido", "Desconto indevido"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data_devolucao", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("motivo", models.TextField()),
                ("comprovante", models.FileField(upload_to="devolucoes_associado/")),
                ("nome_comprovante", models.CharField(blank=True, max_length=255)),
                ("competencia_referencia", models.DateField(blank=True, null=True)),
                ("nome_snapshot", models.CharField(max_length=255)),
                ("cpf_cnpj_snapshot", models.CharField(max_length=20)),
                ("matricula_snapshot", models.CharField(blank=True, max_length=60)),
                ("agente_snapshot", models.CharField(blank=True, max_length=255)),
                ("contrato_codigo_snapshot", models.CharField(max_length=80)),
                ("revertida_em", models.DateTimeField(blank=True, null=True)),
                ("motivo_reversao", models.TextField(blank=True)),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes_associado",
                        to="associados.associado",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes_associado",
                        to="contratos.contrato",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes_associado_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revertida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devolucoes_associado_revertidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_devolucao", "-created_at", "-id"],
            },
        ),
    ]
