# Generated by Django 6.0.2 on 2026-03-22 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesouraria", "0009_devolucaoassociado"),
    ]

    operations = [
        migrations.AddField(
            model_name="devolucaoassociado",
            name="quantidade_parcelas",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="DevolucaoAssociadoAnexo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("data_referencia_negocio", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("arquivo", models.FileField(upload_to="devolucoes_associado/")),
                ("nome_arquivo", models.CharField(blank=True, max_length=255)),
                (
                    "devolucao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="tesouraria.devolucaoassociado",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
