# Generated by Django 5.0.4 on 2026-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0012_liquidacaocontrato_origem_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucaoassociado',
            name='tipo',
            field=models.CharField(choices=[('pagamento_indevido', 'Pagamento indevido'), ('desconto_indevido', 'Desconto indevido'), ('desistencia_pos_liquidacao', 'Desistência pós-liquidação')], max_length=30),
        ),
    ]
